CREATE TABLE companies (
  id SERIAL PRIMARY KEY,
  inn VARCHAR(20) NOT NULL UNIQUE,
  kpp VARCHAR(20),
  company_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_companies_inn ON companies(inn);