CREATE TABLE property_values (
    id BIGSERIAL PRIMARY KEY,
    key VARCHAR(50) NOT NULL UNIQUE,
    slug VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,
    property_uuid UUID NOT NULL REFERENCES property(uuid) ON DELETE CASCADE, 
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
